### ISSUE TITLE
Support browsers and data URI

### ISSUE THREAD

**Issue by flesler** [dingram/jsmidgen#10]
This would allow front-ends to generate MIDIs and allow download from a link without any need for a server.

**Comment by dingram** [comment]
It should be possible to support browsers as things stand right now. Something like:

```
<script src="jsmidgen.js"></script>
<script>
var file = new Midi.File();
var track = new Midi.Track();
file.addTrack(track);

track.addNote(0, 'c4', 64);
track.addNote(0, 'd4', 64);
track.addNote(0, 'e4', 64);
track.addNote(0, 'f4', 64);
track.addNote(0, 'g4', 64);
track.addNote(0, 'a4', 64);
track.addNote(0, 'b4', 64);
track.addNote(0, 'c5', 64);

var dataUri = 'data:audio/mid;base64,' + btoa(file.toBytes());
</script>
```

should do the job, I think. I haven't tested that, of course :smile:

If that does work, I'll set up a `toDataUri()` method on `Midi.File` as a convenience.

**Comment by flesler** [comment]
Indeed it does, nice! I'll get started on a little idea of mine, thanks!

**Comment by flesler** [comment]
Sorry, may I bother you with you quick questions?
I'm trying to create a midi based on mouse click holding, using the same note. 
- I have a note duration in milliseconds, how to I translate that to ticks precisely?
- How do I add silences between notes, using the same duration strategy?

Thanks

**Comment by dingram** [comment]
Currently, jsmidgen hardcodes a rate of 128 ticks per beat, and you can set the number of beats per minute by calling `setTempo(120)` (or whatever value) on a `Track` object.

If you want ticks to translate to milliseconds, you could perhaps do this by changing the structure of the file. Firstly, you'd need to override the hardcoded rate of ticks per beat:

```
// Override files to write 1000 ticks per beat
Midi.File.HDR_SPEED       = "\x03\xe8";
```

Then you would want to set the tempo to 60 BPM:

```
track.setTempo(60);
```

This way, there are 1000 ticks per beat, and 60 beats per minute.

Could you please open an issue about adding the ability to set the number of ticks per beat?

**Comment by dingram** [comment]
Oh, and if you're looking to add silences, you may want to use `addNoteOn()` and `addNoteOff()`. Simply call `addNoteOn()` on click and `addNoteOff()` on release, passing the time since the last release/click event as appropriate.

**Comment by flesler** [comment]
But what note should be used for a silent note?

**Comment by dingram** [comment]
Something like:

```
// time of the last mouse click/release
var lastEventTime = 0;

thing.on('mousedown', function(){
  // time of this midi event (in ms since the last event)
  // defaults to zero for the first ever note
  var time = 0;
  if (lastEventTime) {
    // calculate the ms since the last event
    var now = +new Date();
    time = now - lastEventTime;
    // record the current time
    lastEventTime = now;
  }
  // add the note
  track.addNoteOn(0, 'c4', time);
});

thing.on('mouseup', function(){
  if (!lastEventTime) {
    throw new Error('Cannot process an end-of-note if there was no start!');
  }
  var now = +new Date();
  var time = now - lastEventTime;
  lastEventTime = now;
  track.addNoteOff(0, 'c4', time);
});
```

**Comment by dingram** [comment]
(If you saw this immediately, be aware that I edited it slightly as I realized it had an error).

**Comment by flesler** [comment]
Perfect, I actually made a very similar piece of code, assumed had to pass it on addNoteOn. Mind you it now hangs for several seconds when I generate the midi, I supposed due to the change to ticks per beat. I will try lowering it down.
