### ISSUE TITLE
End of Track Event should have no data

### ISSUE THREAD

**Issue by JackCA** [dingram/jsmidgen#16]
[This line](https://github.com/dingram/jsmidgen/blob/c631d10e34868c48e5a1e2d197f165a0c6eefc21/lib/jsmidgen.js#L254) assumes that a `MetaEvent` is invalid unless it has `data`; however, from what I understand the      EOT event *should not* have any data.

Passing in any truthy `data` alongside a `Midi.MetaEvent.END_OF_TRACK` will result in a `Error: fluidsynth: error: Invalid length for EndOfTrack event` when using something like fluidsynth.

I am having trouble tracking down where this rule is defined in docs and am having trouble pinpointing it...

**Comment by dingram** [comment]
You're correct: https://www.csie.ntu.edu.tw/~r92092/ref/midi/#meta_event

**Comment by dingram** [comment]
Fixed in 4959b7a1848a28022d49b48ecbd591b8877ff5bc

**Comment by JackCA** [comment]
:clap: :clap: :clap:!
