### ISSUE TITLE
Notes are rendered an octave lower

### ISSUE THREAD

**Issue by walmik** [dingram/jsmidgen#20]
Execute the following script to create a MIDI file that contains a single C4 note. Import the MIDI file in a software like Garage Band or Ableton Live. The generated note will show C3.

```
var Midi = require('jsmidgen');
var fs = require('fs');

var file = new Midi.File();
var track = new Midi.Track();
file.addTrack(track);

track.addNote(0, 'c4', 64);

fs.writeFileSync('test.mid', file.toBytes(), 'binary');
```

**Comment by walmik** [comment]
On second thoughts I m not entirely sure this is an issue. Ableton Live (and presumable Garage Band too) considers C3 as the middle C. The only issue then is, what do most people do with the MIDI files generated using `jsmidgen`? If they are gonna use a software to make use of the MIDI files, then they are gonna be thrown off by this. Should we have a mechanism to adjust middle C based on user preference?

**Comment by dingram** [comment]
https://en.wikipedia.org/wiki/Scientific_pitch_notation suggests that C4 is *always* middle C, which should be in line with what `jsmidgen` produces.

**Comment by walmik** [comment]
Agreed. And I spoke to a musician friend and he too confirmed this, but there seems to be this second school of thought when it comes to music software. For example even in Propellerhead Reason's NNXT sampler C3 is the middle C. I dont have FL Studio, but looks like there too its not C4.

The MIDI (Musical Instrument Device Interface) standards unfortunately do not designate octaves. They just specify the number 60 as the middle C leaving the octave itself to the implementors. My concern is toward the users of this lib who will import the generated MIDI files in to softwares. I m one of them :)

**Comment by walmik** [comment]
Confirming C4 as the middle octave.
