### ISSUE TITLE
Unable to save .mid file as blob

### ISSUE THREAD

**Issue by dorev** [dingram/jsmidgen#41]
I wrote a post about this on StackOverflow, but I think it's worth to mention it here.

https://stackoverflow.com/q/57129828/3038149

Thanks!

**Comment by walmik** [comment]
@dorev Thanks for the mention here (i d ve missed the stackoverflow question).. I ve responded there.. Hope it addresses it :)

**Comment by dorev** [comment]
I've just tried locally and nothing seems to happen, is this the kind of thing that only works once it is deployed? (sorry I'm still new to the javascript/browser universe!) I'm working with Firefox.
