### ISSUE TITLE
How do you trigger two notes at the same time?

### ISSUE THREAD

**Issue by domhofmann** [dingram/jsmidgen#7]
It seems like `time` in tracks is relative to the duration of the last noteOn. What if I want two noteOns at the same time?

**Comment by dingram** [comment]
The docs could use some clarity here, but you can produce a chord by only passing two arguments to `noteOn` or by using a zero for the third argument. In the example in the `README`, after the instrument is changed to "church organ", it plays two C major chords.

**Comment by domhofmann** [comment]
Sorry to bother, but I'm still running into odd behavior. I think this might just be the way MIDI is, however.

Assuming I have a list of absolute times (in ticks), how would I map that to `time`? I have success playing two notes together, but it looks like all subsequent notes base their `time` on the notes that came before.

**Comment by dingram** [comment]
MIDI is all based on relative times since the last note. In order to convert absolute times to relative, you'll need to iterate through the list of notes in ascending order of start time. I don't know what sort of data you have, so I'll make it up:

```javascript
// data has absolute start and end times for each pitch
var data = [
  {start: 0, end: 15, pitch: 'c4'},
  {start: 60, end: 70, pitch: 'c5'},
  {start: 0, end: 30, pitch: 'e4'},
  {start: 0, end: 45, pitch: 'g4'},
];

var processed_data = [];
data.forEach(function(e){
  // add an on and off event at their absolute times
  processed_data.push({on: true, time: e.start, pitch: e.pitch});
  processed_data.push({on: false, time: e.end, pitch: e.pitch});
});

// make sure the events are ordered by their times
processed_data.sort(function(a, b){ return a.time - b.time; });
var track = /* the MIDI track */;

// the last time we saw
var last_time = 0;
sorted_data.forEach(function(e){
  // calculate time since last event
  var relwhen = e.time - last_time;
  if (e.on) {
    track.addNoteOn(1, e.pitch, relwhen);
  } else {
    track.addNoteOff(1, e.pitch, relwhen);
  }
  // this is now the biggest event we've seen
  last_time = e.time;
});
```

I haven't tested this code at all; just wrote it off the top of my head... but it should give you the general idea :-)
