### ISSUE TITLE
Do multiple tracks work?

### ISSUE THREAD

**Issue by domhofmann** [dingram/jsmidgen#8]
I'm not having any luck getting multiple tracks to export, even though the `track` count and their corresponding `events` properties appear to match.

**Comment by domhofmann** [comment]
Test code:

```javascript
file = new midi.File();
file
  .addTrack()

    .note(0, 'c4', 32)
    .note(0, 'd4', 32)
    .note(0, 'e4', 32)
    .note(0, 'f4', 32)
    .note(0, 'g4', 32)
    .note(0, 'a4', 32)
    .note(0, 'b4', 32)
    .note(0, 'c5', 32)
    // church organ

file
    .addTrack()
    .instrument(1, 0x13)

    // by skipping the third arguments, we create a chord (C major)
    .noteOn(1, 'c4', 64)
    .noteOn(1, 'e4')
    .noteOn(1, 'g4')
    // by skipping the third arguments again, we stop all notes at once
    .noteOff(1, 'c4', 47)
    .noteOff(1, 'e4')
    .noteOff(1, 'g4')

    .noteOn(1, 'c4', 1)
    .noteOn(1, 'e4')
    .noteOn(1, 'g4')
    .noteOff(1, 'c4', 384)
    .noteOff(1, 'e4')
    .noteOff(1, 'g4');

fs.writeFileSync('test2.mid', file.toBytes(), 'binary')
```

**Comment by dingram** [comment]
Do you mind sharing why you closed the issue? Did you find the problem? If so, what was it?

**Comment by xrochoa** [comment]
Hi. First congrats on the plugin. It's been very useful so far. 
I'm having this same issue using when adding multiple tracks. The binary output file seems to get longer when adding more tracks but when importing to Logic Pro X, I only get the first one. I would guess it is related with how logic handles midi format. I tried adding other standard midi files to Logic Pro and I get all the tracks. I'm thinking that you are probably missing something in the midi specification. Do you have any ideas on how to fix that? Thanks.
